name: flutter_lion_components
version: 0.1.0
homepage: https://github.com/BooManLag/flutter_lion_components
repository: https://github.com/BooManLag/flutter_lion_components
issue_tracker: https://github.com/BooManLag/flutter_lion_components/issues

description: A Flutter UI component library inspired by Lion Web Components. Provides accessible, themable, and reusable form components.

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
